module.exports = {
    up: async (queryInterface, Sequelize) => {
      await queryInterface.bulkInsert('Vacancies', [
        {
          title: 'Frontend Developer',
          description: 'Разработка пользовательских интерфейсов.',
          companyName: 'TechCorp',
          location: 'Москва',
          salary: 120000,
          englishLvl: 'Intermediate',
          grade: 'Middle',
          tags: 'JavaScript, React, HTML, CSS',
          is_active: true,
          experience: '1-3 года',
          skills: 'JavaScript, React, Redux',
          employmentType: 'Полная занятость',
          category_id: 'IT',
        },
        {
          title: 'Backend Developer',
          description: 'Разработка серверной части приложений.',
          companyName: 'TechCorp',
          location: 'Санкт-Петербург',
          salary: 140000,
          englishLvl: 'Upper-Intermediate',
          grade: 'Senior',
          tags: 'Node.js, PostgreSQL, Docker',
          is_active: true,
          experience: '3+ года',
          skills: 'Node.js, Express, SQL',
          employmentType: 'Полная занятость',
          category_id: 'IT',
        },
        {
          title: 'Data Scientist',
          description: 'Анализ данных и построение моделей машинного обучения.',
          companyName: 'DataWorks',
          location: 'Новосибирск',
          salary: 150000,
          englishLvl: 'Advanced',
          grade: 'Senior',
          tags: 'Python, Machine Learning, TensorFlow',
          is_active: true,
          experience: '3+ года',
          skills: 'Python, Pandas, Scikit-learn',
          employmentType: 'Удаленная работа',
          category_id: 'Data Science',
        },
        {
          title: 'DevOps Engineer',
          description: 'Настройка CI/CD и управление инфраструктурой.',
          companyName: 'DataWorks',
          location: 'Екатеринбург',
          salary: 160000,
          englishLvl: 'Upper-Intermediate',
          grade: 'Middle',
          tags: 'Docker, Kubernetes, AWS',
          is_active: true,
          experience: '2+ года',
          skills: 'Linux, Bash, Ansible',
          employmentType: 'Полная занятость',
          category_id: 'DevOps',
        },
        {
          title: 'UI/UX Designer',
          description: 'Создание дизайна интерфейсов.',
          companyName: 'DesignStudio',
          location: 'Казань',
          salary: 90000,
          englishLvl: 'Pre-Intermediate',
          grade: 'Junior',
          tags: 'Figma, Adobe XD, Sketch',
          is_active: true,
          experience: 'Без опыта',
          skills: 'Figma, Photoshop, Illustrator',
          employmentType: 'Частичная занятость',
          category_id: 'Design',
        },
        {
          title: 'Product Manager',
          description: 'Управление продуктом и командой разработки.',
          companyName: 'DesignStudio',
          location: 'Уфа',
          salary: 130000,
          englishLvl: 'Intermediate',
          grade: 'Middle',
          tags: 'Agile, Scrum, Product Management',
          is_active: true,
          experience: '2+ года',
          skills: 'Jira, Confluence, Roadmapping',
          employmentType: 'Полная занятость',
          category_id: 'Management',
        },
        {
          title: 'Mobile Developer',
          description: 'Разработка мобильных приложений.',
          companyName: 'AppMakers',
          location: 'Краснодар',
          salary: 110000,
          englishLvl: 'Intermediate',
          grade: 'Middle',
          tags: 'React Native, Swift, Kotlin',
          is_active: true,
          experience: '1-3 года',
          skills: 'React Native, JavaScript, Redux',
          employmentType: 'Полная занятость',
          category_id: 'Mobile Development',
        },
        {
          title: 'QA Engineer',
          description: 'Тестирование веб- и мобильных приложений.',
          companyName: 'AppMakers',
          location: 'Воронеж',
          salary: 80000,
          englishLvl: 'Pre-Intermediate',
          grade: 'Junior',
          tags: 'Manual Testing, Automated Testing, Selenium',
          is_active: true,
          experience: 'Без опыта',
          skills: 'Test Cases, Bug Tracking, SQL',
          employmentType: 'Полная занятость',
          category_id: 'QA',
        },
        {
          title: 'Marketing Specialist',
          description: 'Продвижение продуктов компании.',
          companyName: 'MarketGurus',
          location: 'Ростов-на-Дону',
          salary: 70000,
          englishLvl: 'Intermediate',
          grade: 'Junior',
          tags: 'SEO, SMM, Google Analytics',
          is_active: true,
          experience: '1 год',
          skills: 'SEO, Content Marketing, Social Media',
          employmentType: 'Полная занятость',
          category_id: 'Marketing',
        },
        {
          title: 'Content Manager',
          description: 'Создание и редактирование контента.',
          companyName: 'MarketGurus',
          location: 'Самара',
          salary: 60000,
          englishLvl: 'Pre-Intermediate',
          grade: 'Junior',
          tags: 'Copywriting, Editing, CMS',
          is_active: true,
          experience: 'Без опыта',
          skills: 'WordPress, HTML, SEO',
          employmentType: 'Частичная занятость',
          category_id: 'Marketing',
        },
        {
            title: 'Full-Stack Developer',
            description: 'Разработка и поддержка веб-приложений. Взаимодействие с клиентами для уточнения требований. Оптимизация производительности приложений. Работа с современными технологиями, такими как React, Node.js и MongoDB.',
            companyName: 'TechCorp',
            location: 'Москва',
            salary: 150000,
            englishLvl: 'Upper-Intermediate',
            grade: 'Senior',
            tags: 'JavaScript, React, Node.js, MongoDB',
            is_active: true,
            experience: '3+ года',
            skills: 'JavaScript, React, Node.js, REST API',
            employmentType: 'Полная занятость',
            category_id: 'IT',
          },
          {
            title: 'System Administrator',
            description: 'Обслуживание и настройка серверов. Мониторинг и устранение неисправностей. Управление сетевыми ресурсами. Обеспечение безопасности и резервного копирования данных.',
            companyName: 'TechCorp',
            location: 'Санкт-Петербург',
            salary: 90000,
            englishLvl: 'Intermediate',
            grade: 'Middle',
            tags: 'Linux, Windows, Networking, Security',
            is_active: true,
            experience: '2+ года',
            skills: 'Linux, Bash, Ansible, Docker',
            employmentType: 'Полная занятость',
            category_id: 'IT',
          },
          {
            title: 'Big Data Engineer',
            description: 'Разработка и поддержка систем обработки больших данных. Работа с Hadoop, Spark и Kafka. Оптимизация ETL-процессов. Взаимодействие с аналитиками и разработчиками.',
            companyName: 'DataWorks',
            location: 'Новосибирск',
            salary: 170000,
            englishLvl: 'Advanced',
            grade: 'Senior',
            tags: 'Hadoop, Spark, Kafka, Big Data',
            is_active: true,
            experience: '3+ года',
            skills: 'Hadoop, Spark, Python, SQL',
            employmentType: 'Удаленная работа',
            category_id: 'Data Science',
          },
          {
            title: 'Data Analyst',
            description: 'Анализ данных и подготовка отчетов. Визуализация данных с использованием Tableau или Power BI. Работа с SQL и Python. Поддержка принятия решений на основе данных.',
            companyName: 'DataWorks',
            location: 'Екатеринбург',
            salary: 110000,
            englishLvl: 'Intermediate',
            grade: 'Middle',
            tags: 'SQL, Python, Tableau, Data Analysis',
            is_active: true,
            experience: '1-3 года',
            skills: 'SQL, Python, Excel, Tableau',
            employmentType: 'Полная занятость',
            category_id: 'Data Science',
          },
          {
            title: 'Graphic Designer',
            description: 'Создание графического контента для рекламных кампаний. Разработка логотипов, баннеров и иллюстраций. Работа с Adobe Photoshop, Illustrator и InDesign.',
            companyName: 'DesignStudio',
            location: 'Казань',
            salary: 80000,
            englishLvl: 'Pre-Intermediate',
            grade: 'Junior',
            tags: 'Photoshop, Illustrator, Graphic Design',
            is_active: true,
            experience: '1 год',
            skills: 'Photoshop, Illustrator, InDesign',
            employmentType: 'Частичная занятость',
            category_id: 'Design',
          },
          {
            title: 'Web Designer',
            description: 'Создание дизайна веб-сайтов и мобильных приложений. Прототипирование и разработка пользовательских интерфейсов. Работа с Figma и Adobe XD.',
            companyName: 'DesignStudio',
            location: 'Уфа',
            salary: 100000,
            englishLvl: 'Intermediate',
            grade: 'Middle',
            tags: 'Figma, Adobe XD, UI/UX Design',
            is_active: true,
            experience: '2+ года',
            skills: 'Figma, Adobe XD, HTML, CSS',
            employmentType: 'Полная занятость',
            category_id: 'Design',
          },
          {
            title: 'iOS Developer',
            description: 'Разработка мобильных приложений для iOS. Работа с Swift и Objective-C. Интеграция с REST API. Участие в полном цикле разработки, от идеи до релиза.',
            companyName: 'AppMakers',
            location: 'Краснодар',
            salary: 130000,
            englishLvl: 'Intermediate',
            grade: 'Middle',
            tags: 'Swift, Objective-C, iOS Development',
            is_active: true,
            experience: '2+ года',
            skills: 'Swift, Objective-C, Xcode, REST API',
            employmentType: 'Полная занятость',
            category_id: 'Mobile Development',
          },
          {
            title: 'Android Developer',
            description: 'Разработка мобильных приложений для Android. Работа с Kotlin и Java. Интеграция с внешними API. Оптимизация производительности приложений.',
            companyName: 'AppMakers',
            location: 'Воронеж',
            salary: 120000,
            englishLvl: 'Intermediate',
            grade: 'Middle',
            tags: 'Kotlin, Java, Android Development',
            is_active: true,
            experience: '2+ года',
            skills: 'Kotlin, Java, Android Studio, REST API',
            employmentType: 'Полная занятость',
            category_id: 'Mobile Development',
          },
          {
            title: 'SEO Specialist',
            description: 'Оптимизация сайтов для поисковых систем. Проведение аудитов и анализ ключевых слов. Разработка и реализация SEO-стратегий. Работа с инструментами, такими как Google Analytics и Ahrefs.',
            companyName: 'MarketGurus',
            location: 'Ростов-на-Дону',
            salary: 90000,
            englishLvl: 'Intermediate',
            grade: 'Middle',
            tags: 'SEO, Google Analytics, Ahrefs',
            is_active: true,
            experience: '2+ года',
            skills: 'SEO, Google Analytics, Keyword Research',
            employmentType: 'Полная занятость',
            category_id: 'Marketing',
          },
          {
            title: 'SMM Manager',
            description: 'Управление социальными сетями компании. Создание контента и планирование публикаций. Анализ эффективности кампаний. Взаимодействие с подписчиками и рекламодателями.',
            companyName: 'MarketGurus',
            location: 'Самара',
            salary: 70000,
            englishLvl: 'Pre-Intermediate',
            grade: 'Junior',
            tags: 'SMM, Content Creation, Social Media',
            is_active: true,
            experience: '1 год',
            skills: 'Instagram, Facebook, TikTok, Analytics',
            employmentType: 'Частичная занятость',
            category_id: 'Marketing',
          },
          {
            title: 'Cloud Engineer',
            description: 'Разработка и поддержка облачной инфраструктуры. Работа с AWS, Azure или Google Cloud. Настройка виртуальных машин, контейнеров и сетей. Обеспечение безопасности и масштабируемости облачных решений.',
            companyName: 'TechCorp',
            location: 'Москва',
            salary: 160000,
            englishLvl: 'Upper-Intermediate',
            grade: 'Senior',
            tags: 'AWS, Azure, Google Cloud, Docker',
            is_active: true,
            experience: '3+ года',
            skills: 'AWS, Kubernetes, Terraform, CI/CD',
            employmentType: 'Полная занятость',
            category_id: 'DevOps',
          },
          {
            title: 'QA Automation Engineer',
            description: 'Разработка и поддержка автоматизированных тестов. Работа с Selenium, Cypress или Playwright. Интеграция тестов в CI/CD. Анализ результатов тестирования и отчетность.',
            companyName: 'TechCorp',
            location: 'Санкт-Петербург',
            salary: 130000,
            englishLvl: 'Intermediate',
            grade: 'Middle',
            tags: 'Selenium, Cypress, Automated Testing',
            is_active: true,
            experience: '2+ года',
            skills: 'Selenium, Python, Jenkins, Git',
            employmentType: 'Полная занятость',
            category_id: 'QA',
          },
          {
            title: 'Machine Learning Engineer',
            description: 'Разработка и внедрение моделей машинного обучения. Работа с TensorFlow, PyTorch и Scikit-learn. Обработка и анализ данных. Оптимизация алгоритмов для повышения производительности.',
            companyName: 'DataWorks',
            location: 'Новосибирск',
            salary: 180000,
            englishLvl: 'Advanced',
            grade: 'Senior',
            tags: 'Machine Learning, Python, TensorFlow',
            is_active: true,
            experience: '3+ года',
            skills: 'Python, TensorFlow, PyTorch, SQL',
            employmentType: 'Удаленная работа',
            category_id: 'Data Science',
          },
          {
            title: 'Business Intelligence Analyst',
            description: 'Анализ данных для поддержки бизнес-решений. Создание отчетов и дашбордов. Работа с BI-инструментами, такими как Power BI или Tableau. Взаимодействие с отделами компании для сбора требований.',
            companyName: 'DataWorks',
            location: 'Екатеринбург',
            salary: 120000,
            englishLvl: 'Intermediate',
            grade: 'Middle',
            tags: 'Power BI, Tableau, Data Analysis',
            is_active: true,
            experience: '2+ года',
            skills: 'SQL, Power BI, Excel, Data Visualization',
            employmentType: 'Полная занятость',
            category_id: 'Data Science',
          },
          {
            title: '3D Artist',
            description: 'Создание 3D-моделей для игр и рекламы. Работа с Blender, Maya или 3ds Max. Текстурирование и анимация. Взаимодействие с дизайнерами и разработчиками.',
            companyName: 'DesignStudio',
            location: 'Казань',
            salary: 100000,
            englishLvl: 'Pre-Intermediate',
            grade: 'Middle',
            tags: 'Blender, Maya, 3D Modeling',
            is_active: true,
            experience: '2+ года',
            skills: 'Blender, Maya, Texturing, Animation',
            employmentType: 'Полная занятость',
            category_id: 'Design',
          },
          {
            title: 'Motion Designer',
            description: 'Создание анимации для рекламы и видеоконтента. Работа с After Effects и Premiere Pro. Разработка креативных концепций. Взаимодействие с командой маркетинга.',
            companyName: 'DesignStudio',
            location: 'Уфа',
            salary: 90000,
            englishLvl: 'Intermediate',
            grade: 'Middle',
            tags: 'After Effects, Premiere Pro, Motion Design',
            is_active: true,
            experience: '2+ года',
            skills: 'After Effects, Premiere Pro, Animation',
            employmentType: 'Полная занятость',
            category_id: 'Design',
          },
          {
            title: 'Flutter Developer',
            description: 'Разработка кросс-платформенных мобильных приложений. Работа с Flutter и Dart. Интеграция с REST API. Участие в полном цикле разработки, от проектирования до релиза.',
            companyName: 'AppMakers',
            location: 'Краснодар',
            salary: 140000,
            englishLvl: 'Intermediate',
            grade: 'Middle',
            tags: 'Flutter, Dart, Mobile Development',
            is_active: true,
            experience: '2+ года',
            skills: 'Flutter, Dart, REST API, Firebase',
            employmentType: 'Полная занятость',
            category_id: 'Mobile Development',
          },
          {
            title: 'Unity Developer',
            description: 'Разработка игр и приложений с использованием Unity. Работа с C# и 3D-графикой. Оптимизация производительности. Взаимодействие с дизайнерами и художниками.',
            companyName: 'AppMakers',
            location: 'Воронеж',
            salary: 130000,
            englishLvl: 'Intermediate',
            grade: 'Middle',
            tags: 'Unity, C#, Game Development',
            is_active: true,
            experience: '2+ года',
            skills: 'Unity, C#, 3D Graphics, Game Design',
            employmentType: 'Полная занятость',
            category_id: 'Game Development',
          },
          {
            title: 'PPC Specialist',
            description: 'Управление рекламными кампаниями в Google Ads и Яндекс.Директ. Анализ эффективности кампаний. Оптимизация бюджета и ключевых слов. Подготовка отчетов.',
            companyName: 'MarketGurus',
            location: 'Ростов-на-Дону',
            salary: 95000,
            englishLvl: 'Intermediate',
            grade: 'Middle',
            tags: 'Google Ads, Яндекс.Директ, PPC',
            is_active: true,
            experience: '2+ года',
            skills: 'Google Ads, Яндекс.Директ, Analytics',
            employmentType: 'Полная занятость',
            category_id: 'Marketing',
          },
          {
            title: 'Content Writer',
            description: 'Создание текстового контента для сайтов, блогов и социальных сетей. Написание SEO-оптимизированных статей. Редактирование и корректура текстов. Взаимодействие с маркетинговой командой.',
            companyName: 'MarketGurus',
            location: 'Самара',
            salary: 60000,
            englishLvl: 'Pre-Intermediate',
            grade: 'Junior',
            tags: 'Copywriting, SEO, Content Creation',
            is_active: true,
            experience: '1 год',
            skills: 'SEO, Copywriting, Grammar, Research',
            employmentType: 'Частичная занятость',
            category_id: 'Marketing',
          },
          {
            title: 'Blockchain Developer',
            description: 'Разработка смарт-контрактов и блокчейн-решений. Работа с Ethereum, Solidity и Web3.js. Создание децентрализованных приложений (dApps). Взаимодействие с командой разработки.',
            companyName: 'TechCorp',
            location: 'Москва',
            salary: 200000,
            englishLvl: 'Advanced',
            grade: 'Senior',
            tags: 'Blockchain, Ethereum, Solidity',
            is_active: true,
            experience: '3+ года',
            skills: 'Solidity, Ethereum, Web3.js, Smart Contracts',
            employmentType: 'Полная занятость',
            category_id: 'Blockchain',
          },
          {
            title: 'Cybersecurity Specialist',
            description: 'Обеспечение безопасности IT-инфраструктуры. Проведение аудитов и тестирование на проникновение. Разработка политик безопасности. Мониторинг и предотвращение угроз.',
            companyName: 'TechCorp',
            location: 'Санкт-Петербург',
            salary: 170000,
            englishLvl: 'Upper-Intermediate',
            grade: 'Senior',
            tags: 'Cybersecurity, Penetration Testing, Firewalls',
            is_active: true,
            experience: '3+ года',
            skills: 'Penetration Testing, Firewalls, SIEM',
            employmentType: 'Полная занятость',
            category_id: 'Security',
          },
          {
            title: 'AR/VR Developer',
            description: 'Разработка приложений дополненной и виртуальной реальности. Работа с Unity и ARKit/ARCore. Создание интерактивных 3D-сцен. Взаимодействие с дизайнерами и тестировщиками.',
            companyName: 'AppMakers',
            location: 'Краснодар',
            salary: 150000,
            englishLvl: 'Intermediate',
            grade: 'Middle',
            tags: 'AR, VR, Unity, 3D Development',
            is_active: true,
            experience: '2+ года',
            skills: 'Unity, ARKit, ARCore, 3D Modeling',
            employmentType: 'Полная занятость',
            category_id: 'Game Development',
          },
          {
            title: 'Technical Writer',
            description: 'Создание технической документации для продуктов компании. Написание руководств, API-документации и FAQ. Взаимодействие с разработчиками и тестировщиками.',
            companyName: 'TechCorp',
            location: 'Москва',
            salary: 90000,
            englishLvl: 'Upper-Intermediate',
            grade: 'Middle',
            tags: 'Technical Writing, Documentation, API',
            is_active: true,
            experience: '2+ года',
            skills: 'Technical Writing, Markdown, API Documentation',
            employmentType: 'Полная занятость',
            category_id: 'Technical Writing',
          },
          {
            title: 'Customer Support Specialist',
            description: 'Обработка запросов клиентов через чат, email и телефон. Решение проблем и консультация по продуктам. Ведение базы знаний. Взаимодействие с технической поддержкой.',
            companyName: 'MarketGurus',
            location: 'Самара',
            salary: 50000,
            englishLvl: 'Pre-Intermediate',
            grade: 'Junior',
            tags: 'Customer Support, Communication, CRM',
            is_active: true,
            experience: 'Без опыта',
            skills: 'Communication, CRM, Problem Solving',
            employmentType: 'Полная занятость',
            category_id: 'Support',
          },
      ], {});
    },
  
    down: async (queryInterface, Sequelize) => {
      await queryInterface.bulkDelete('Vacancies', null, {});
    }
  };